<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Tenant;

/**
 * TenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Tenant $tenant)
    {
        $this->getEntityManager()->persist($tenant);
        $this->getEntityManager()->flush();
    }

    public function findById($id)
    {
        return $this->find($id);
    }
}
